version: '2'

networks:
  traefik:
    external:
      name: traefik_webgateway

services:
  npm:
    image: node:8.2
    volumes:
      - ./:/var/www/bitterballen
    working_dir: /var/www/bitterballen
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=bitterballen-client-web"
      - "traefik.frontend.rule=Host:bitterballen.dev "
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_webgateway"

  yarn:
    image: kkarczmarczyk/node-yarn:8.0
    volumes:
      - ./:/var/www/bitterballen
    working_dir: /var/www/bitterballen
    command: yarn
